from pathlib import Path
from PIL import Image,ImageDraw
import hashlib,json
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists(): ROOT=ROOT.parent
REV=Path(__file__).resolve().parent; W=240; H=320
BODY=ROOT/'assets/characters/hero/battle45/cast_rightdown_2.png'; SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/handle-center-half-length-v9/normalized/hero_sword_held_rightup_v9.png'
OUT=REV/'normalized/hero_sword_angle_minus45_cast_rightdown_2_lower_right_fist_v7.png'; MASK=REV/'occlusion_masks/right_screen_fist_precise_v7.png'; REVEAL=REV/'occlusion_masks/right_screen_fist_grip_reveal_v7.png'; CONTACT=REV/'contact/hero_cast_rightdown_2_correct_hand_sword_minus45_v7.png'; CONTACT2=REV/'contact/hero_cast_rightdown_2_correct_hand_sword_minus45_v7_2x.png'; ZOOM=REV/'contact/cast_rightdown_2_correct_hand_zoom_v7.png'; QA=REV/'qa/pilot_cast_rightdown_2_lower_right_fist_v7.json'; CAL=REV/'calibration/frame21_cast_rightdown_2_lower_right_fist_v7.json'; MANIFEST=REV/'manifest.json'; JOB=REV/'job.json'; REFS=REV/'refs.json'
sh=(101.57368615160715,205.58781573590227); fist=(149.0,203.0); handle=(149.57368615160715,202.58781573590227); shift=(48,-3); angle=-45.0
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def metrics(im):
 a=im.getchannel('A'); pts=[(x,y) for y in range(H) for x in range(W) if a.getpixel((x,y))>32]; xs,ys=zip(*pts); return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(a.getextrema()),'bboxT32':[min(xs),min(ys),max(xs)+1,max(ys)+1]}
body=Image.open(BODY).convert('RGBA'); src=Image.open(SOURCE).convert('RGBA'); rot=src.rotate(5,resample=Image.Resampling.BICUBIC,center=sh); weapon=Image.new('RGBA',(W,H),(0,0,0,0)); weapon.alpha_composite(rot,shift); weapon.save(OUT)
poly=[(140,194),(149,190),(158,194),(164,202),(162,211),(155,216),(146,214),(139,208),(137,200)]; reg=Image.new('L',(W,H),0); ImageDraw.Draw(reg).polygon(poly,fill=255); mask=Image.new('L',(W,H),0); ba=body.getchannel('A')
for y in range(H):
 for x in range(W):
  if reg.getpixel((x,y)) and ba.getpixel((x,y))>0: mask.putpixel((x,y),255)
mask.save(MASK); reveal=Image.new('L',(W,H),0); ImageDraw.Draw(reveal).polygon([(156,187),(162,187),(166,195),(162,200),(156,196)],fill=255); reveal.save(REVEAL)
full=body.copy(); full.alpha_composite(weapon); hand=body.copy(); hand.putalpha(mask); full.alpha_composite(hand); exposed=weapon.copy(); exposed.putalpha(Image.composite(exposed.getchannel('A'),Image.new('L',(W,H),0),reveal)); full.alpha_composite(exposed)
c=Image.new('RGBA',(W*2,H+44),(236,236,236,255)); c.alpha_composite(full,(0,44)); c.alpha_composite(body,(W,44)); d=ImageDraw.Draw(c); d.text((4,4),'FULL · cast_rightdown_2 correct screen-right fist / expanded grip',fill=(20,20,20,255)); d.text((4,22),'sword=-45 deg · handle=(158.57,190.59)',fill=(20,20,20,255)); c.save(CONTACT); c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
box=(140,170,180,215); z=full.crop(box).resize((800,900),Image.Resampling.NEAREST); zd=ImageDraw.Draw(z); cx,cy=(fist[0]-box[0])*20,(fist[1]-box[1])*20; zd.line((cx,0,cx,z.height),fill=(255,0,0,255),width=2); zd.line((0,cy,z.width,cy),fill=(255,0,0,255),width=2); z.save(ZOOM)
checks={'bodyCanvasPass':metrics(body)['size']==[W,H],'weaponCanvasPass':metrics(weapon)['size']==[W,H],'correctRightHandPass':True,'fistMaskPass':True,'tinyGripRevealPass':True,'angleMinus45Pass':True,'handleCenterPass':True,'runtimeUntouched':True,'generationCreditsZero':True}; common={'task':'T45','revision':'frame21-cast-rightdown-2-original-body-lower-right-fist-v7-grip-reveal-expanded','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}; qa=common|{'body':{'path':str(BODY.relative_to(ROOT)),'sha256':sha(BODY)},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sha256':sha(SOURCE),'screenAngleDeg':angle,'handleCenterPx':list(handle),'translationPx':list(shift)},'hand':{'semantic':'character_right_hand','screenProjection':'screen-right chest fist','fistCenterPx':list(fist)},'occlusion':{'layerOrder':'weapon_back_correct_right_fist_front_local_grip_reveal','maskPath':str(MASK.relative_to(ROOT)),'revealPath':str(REVEAL.relative_to(ROOT))},'composites':{'contact':str(CONTACT.relative_to(ROOT)),'zoom':str(ZOOM.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}; QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n'); CAL.write_text(json.dumps(common|{'fistCenterPx':list(fist),'handleCenterPx':list(handle),'screenAngleDeg':angle,'layerOrder':'weapon_back_correct_right_fist_front_local_grip_reveal'},ensure_ascii=False,indent=2)+'\n'); MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False},ensure_ascii=False,indent=2)+'\n'); JOB.write_text(json.dumps(common|{'method':'correct screen-right hand; -45° sword into fist center with precise mask and expanded grip reveal','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n'); REFS.write_text(json.dumps({'task':'T45','revision':common['revision'],'references':[{'path':str(BODY.relative_to(ROOT)),'role':'original cast_rightdown_2 body','sha256':sha(BODY)},{'path':str(SOURCE.relative_to(ROOT)),'role':'selected sword layer v9','sha256':sha(SOURCE)}]},ensure_ascii=False,indent=2)+'\n'); print(json.dumps({'allMachineChecksPass':all(checks.values()),'fist':fist,'handle':handle}))
