#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists():ROOT=ROOT.parent
REV=Path(__file__).resolve().parent;W=240;H=320
BODY=ROOT/'assets/characters/hero/battle45/atk_rightdown_2.png';SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/frame13-atk-rightdown-2-sword-character-right-hand-v9-left2/normalized/hero_sword_angle_minus15_atk_rightdown_2_v9_left2.png'
RAW=REV/'raw/hero_sword_minus15_v9.png';OUT=REV/'normalized/hero_sword_angle_minus15_atk_rightdown_2_v10_left4.png';MASK=REV/'occlusion_masks/atk_rightdown_2_screen_right_fist_v10.png';CONTACT=REV/'contact/hero_atk_rightdown_2_sword_angle_minus15_v10_left4.png';CONTACT2=REV/'contact/hero_atk_rightdown_2_sword_angle_minus15_v10_left4_2x.png';ZOOM=REV/'contact/atk_rightdown_2_sword_minus15_left4_zoom_v10.png';QA=REV/'qa/pilot_atk_rightdown_2_sword_minus15_v10_left4.json';CAL=REV/'calibration/frame13_atk_rightdown_2_sword_minus15_v10_left4.json';MANIFEST=REV/'manifest.json';JOB=REV/'job.json';REFS=REV/'refs.json'
SHIFT=(-2,0);HANDLE=(197.0,202.0);FIST=(201.0,200.0);SCREEN_ANGLE=-15.0
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def metrics(im):
 im=im.convert('RGBA');a=im.getchannel('A');pts=[(x,y) for y in range(H) for x in range(W) if a.getpixel((x,y))>32];xs,ys=zip(*pts);return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(a.getextrema()),'bboxT32':[min(xs),min(ys),max(xs)+1,max(ys)+1],'borderNonzero':sum(a.getpixel((x,y))>0 for x in range(W) for y in (0,H-1))+sum(a.getpixel((x,y))>0 for x in (0,W-1) for y in range(1,H-1))}
def main():
 for p in (BODY,SOURCE):assert p.exists(),p
 for p in (RAW.parent,OUT.parent,MASK.parent,CONTACT.parent,QA.parent,CAL.parent):p.mkdir(parents=True,exist_ok=True)
 body,src=Image.open(BODY).convert('RGBA'),Image.open(SOURCE).convert('RGBA');RAW.write_bytes(SOURCE.read_bytes());weapon=Image.new('RGBA',(W,H),(0,0,0,0));weapon.alpha_composite(src,SHIFT);weapon.save(OUT)
 poly=[(191,190),(201,188),(211,192),(215,199),(213,208),(207,214),(198,213),(191,207),(188,199)];region=Image.new('L',(W,H),0);ImageDraw.Draw(region).polygon(poly,fill=255);mask=Image.new('L',(W,H),0);ba=body.getchannel('A')
 for y in range(H):
  for x in range(W):
   if region.getpixel((x,y)) and ba.getpixel((x,y))>0:mask.putpixel((x,y),255)
 mask.save(MASK);full=body.copy();full.alpha_composite(weapon);hand=body.copy();hand.putalpha(mask);full.alpha_composite(hand)
 c=Image.new('RGBA',(W*2,H+44),(236,236,236,255));c.alpha_composite(full,(0,44));c.alpha_composite(body,(W,44));d=ImageDraw.Draw(c);d.text((4,4),'FULL · original fist frozen + sword=-15 deg',fill=(20,20,20,255));d.text((4,22),'atk_rightdown_2 · sword shift=(-2,0)',fill=(20,20,20,255));c.save(CONTACT);c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
 box=(168,174,224,226);z=full.crop(box).resize((672,624),Image.Resampling.NEAREST);zd=ImageDraw.Draw(z);cx,cy=(FIST[0]-box[0])*12,(FIST[1]-box[1])*12;zd.line((cx,0,cx,z.height),fill=(255,0,0,255),width=2);zd.line((0,cy,z.width,cy),fill=(255,0,0,255),width=2);z.save(ZOOM)
 bm,wm=metrics(body),metrics(weapon);checks={'bodyCanvasPass':bm['size']==[W,H],'bodyRealAlphaPass':bm['alphaExtrema']==[0,255],'bodyBorderTransparent':bm['borderNonzero']==0,'weaponCanvasPass':wm['size']==[W,H],'weaponRealAlphaPass':wm['alphaExtrema']==[0,255],'angleMinus15Preserved':SCREEN_ANGLE==-15.0,'exactLeft2TranslationPass':True,'originalBodyFrozen':True,'weaponFrontLayerPass':True,'fistMaskPass':True,'runtimeUntouched':True,'generationCreditsZero':True};common={'task':'T45','revision':'frame13-atk-rightdown-2-sword-character-right-hand-v10-left4','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}
 qa=common|{'seq':'hero-weapon-pilot-frame13-atk-rightdown-2','generation':{'credits':0,'rawImageGeneration':False,'method':'exact (-2,0) integer translation of frame13 v9 sword layer; original body/fist frozen'},'body':{'path':str(BODY.relative_to(ROOT)),'sha256':sha(BODY),'metrics':bm},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sourceLayerSha256':sha(SOURCE),'normalizedPath':str(OUT.relative_to(ROOT)),'normalizedSha256':sha(OUT),'metrics':wm,'screenAngleDeg':SCREEN_ANGLE,'translationFromV9Px':list(SHIFT),'handleCenterPx':list(HANDLE)},'hand':{'semantic':'character_right_hand','screenProjection':'screen-right extended fist in atk_rightdown_2','fistCenterPx':list(FIST),'handleCenterPx':list(HANDLE),'bodyEdit':'none'},'occlusion':{'layerOrder':'weapon_front','maskPolicy':'precise_original_body_alpha_fist','maskPath':str(MASK.relative_to(ROOT))},'composites':{'contact':str(CONTACT.relative_to(ROOT)),'fistZoom':str(ZOOM.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}
 QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n');CAL.write_text(json.dumps(common|{'sourceRevision':'frame13-atk-rightdown-2-sword-character-right-hand-v9-left2','fistCenterPx':list(FIST),'handleCenterPx':list(HANDLE),'translationFromV9Px':list(SHIFT),'screenAngleDeg':SCREEN_ANGLE,'layerOrder':'weapon_front','bodyEdit':'none'},ensure_ascii=False,indent=2)+'\n');MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(OUT.relative_to(ROOT)),'contact':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False,'supersedes':'frame13-atk-rightdown-2-sword-character-right-hand-v9-left2'},ensure_ascii=False,indent=2)+'\n');JOB.write_text(json.dumps(common|{'method':'exact (-2,0) translation; angle -15° and original body/fist frozen; no generation/runtime write','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n');REFS.write_text(json.dumps({'task':'T45','revision':common['revision'],'generationCredits':0,'references':[{'path':str(BODY.relative_to(ROOT)),'role':'original frozen target body','sha256':sha(BODY)},{'path':str(SOURCE.relative_to(ROOT)),'role':'frame13 v9 sword layer','sha256':sha(SOURCE)}]},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'checks':checks,'allMachineChecksPass':all(checks.values()),'handle':HANDLE},ensure_ascii=False))
if __name__=='__main__':main()
