from pathlib import Path
from PIL import Image,ImageDraw
import hashlib,json
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists():ROOT=ROOT.parent
REV=Path(__file__).resolve().parent; SRC=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/handle-center-half-length-v9/normalized/hero_sword_held_rightup_v9.png'; RAW=REV/'raw/hero_sword_held_rightup_v9_source.png'; RIGHT=REV/'normalized/hero_sword_model_right.png'; LEFT=REV/'normalized/hero_sword_model_left.png'; QA=REV/'qa/sword_model_qa.json'; CAL=REV/'calibration/sword_model_calibration.json'; MAN=REV/'manifest_sword_model.json'; CONTACT=REV/'contact/sword_model_right_left.png'; PROMPT=REV/'prompts/deterministic_export.txt'; BBOX=(90,139,178,219); HANDLE_FULL=(90.57368615160715,215.58781573590227); GRIP_FULL=(113.0,196.0)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
source=Image.open(SRC).convert('RGBA'); RAW.write_bytes(SRC.read_bytes()); right=source.crop(BBOX); left=right.transpose(Image.Transpose.FLIP_LEFT_RIGHT); right.save(RIGHT); left.save(LEFT)
bbox=[0,0,right.width,right.height]; handle=[HANDLE_FULL[0]-BBOX[0],HANDLE_FULL[1]-BBOX[1]]; grip=[GRIP_FULL[0]-BBOX[0],GRIP_FULL[1]-BBOX[1]]
c=Image.new('RGBA',(right.width*2,right.height),(236,236,236,255)); c.alpha_composite(right,(0,0)); c.alpha_composite(left,(right.width,0)); ImageDraw.Draw(c).text((2,2),'RIGHT MODEL | LEFT MIRROR',fill=(20,20,20,255)); c.save(CONTACT)
checks={'sourceCanvasPass':source.size==(240,320),'rightModePass':right.mode=='RGBA','leftModePass':left.mode=='RGBA','rightAlphaPass':right.getchannel('A').getextrema()==(0,255),'leftAlphaPass':left.getchannel('A').getextrema()==(0,255),'bboxT32TightPass':bbox==[0,0,right.width,right.height],'rightShaPass':bool(sha(RIGHT)),'leftShaPass':bool(sha(LEFT)),'zeroGenerationPass':True,'runtimeUntouched':True}
common={'task':'T45','seq':'252','revision':'t45-hero-weapon-sword-model-seq252-v1','artifactStage':'candidate','visualReview':'selected_by_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}
manifest=common|{'source':{'path':str(SRC.relative_to(ROOT)),'sha256':sha(SRC)},'swordModel':{'rightPath':str(RIGHT.relative_to(ROOT)),'rightSha256':sha(RIGHT),'leftPath':str(LEFT.relative_to(ROOT)),'leftSha256':sha(LEFT),'cropBboxFullPx':list(BBOX),'contentBboxModelPx':bbox,'handleOriginModelPx':handle,'gripPointModelPx':grip,'rightBaseAngleDeg':-40.0,'leftBaseAngleDeg':40.0,'angleDefinition':'blade axis from handle/grip toward tip; 0°=screen-right, +Y down, clockwise-positive','flipX':True,'processing':'deterministic tight alpha crop and horizontal mirror; no redraw'} ,'checks':checks|{'allMachineChecksPass':all(checks.values())},'contact':str(CONTACT.relative_to(ROOT))}
QA.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n'); CAL.write_text(json.dumps(common|{'sourceHandleOriginFullPx':list(HANDLE_FULL),'sourceGripPointFullPx':list(GRIP_FULL),'modelHandleOriginPx':handle,'modelGripPointPx':grip,'contentBboxModelPx':bbox,'rightBaseAngleDeg':-40.0,'leftBaseAngleDeg':40.0,'angleDefinition':manifest['swordModel']['angleDefinition']},ensure_ascii=False,indent=2)+'\n'); MAN.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n'); PROMPT.write_text('Deterministic export only. Source v9 selected sword layer; crop tight alpha bbox; preserve pixels; horizontal mirror for left model. No image generation.\n',encoding='utf-8'); print(json.dumps({'checks':checks,'allMachineChecksPass':all(checks.values()),'right':str(RIGHT.relative_to(ROOT)),'left':str(LEFT.relative_to(ROOT)),'handleOriginModelPx':handle,'gripPointModelPx':grip},ensure_ascii=False))
