#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists():ROOT=ROOT.parent
REV=Path(__file__).resolve().parent;W=240;H=320
BODY=ROOT/'assets/characters/hero/battle45/atk_rightup_2.png';SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/frame10-atk-rightup-2-sword-character-right-hand-v6-angle-150/normalized/hero_sword_angle_minus150_atk_rightup_2_v6.png'
RAW=REV/'raw/hero_sword_angle_minus150_v6.png';OUT=REV/'normalized/hero_sword_angle_minus160_atk_rightup_2_v7.png';CONTACT=REV/'contact/hero_atk_rightup_2_sword_angle_minus160_v7.png';CONTACT2=REV/'contact/hero_atk_rightup_2_sword_angle_minus160_v7_2x.png';ZOOM=REV/'contact/atk_rightup_2_angle_minus160_rightdown2_zoom_v7.png';QA=REV/'qa/pilot_atk_rightup_2_angle_minus160_rightdown2_v7.json';CAL=REV/'calibration/frame10_atk_rightup_2_angle_minus160_rightdown2_v7.json';MANIFEST=REV/'manifest.json';JOB=REV/'job.json';REFS=REV/'refs.json'
OLD_HANDLE=(210.57368615160715,96.58781573590227);SHIFT=(2,2);HANDLE=(212.57368615160715,98.58781573590227);FIST=(216.0,96.0);ROTATE_DEG=10.0;SCREEN_ANGLE=-160.0
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def metrics(im):
 im=im.convert('RGBA');a=im.getchannel('A');pts=[(x,y) for y in range(H) for x in range(W) if a.getpixel((x,y))>32];xs,ys=zip(*pts);return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(a.getextrema()),'bboxT32':[min(xs),min(ys),max(xs)+1,max(ys)+1],'borderNonzero':sum(a.getpixel((x,y))>0 for x in range(W) for y in (0,H-1))+sum(a.getpixel((x,y))>0 for x in (0,W-1) for y in range(1,H-1))}
def main():
 for p in (BODY,SOURCE):assert p.exists(),p
 for p in (RAW.parent,OUT.parent,CONTACT.parent,QA.parent,CAL.parent):p.mkdir(parents=True,exist_ok=True)
 body,src=Image.open(BODY).convert('RGBA'),Image.open(SOURCE).convert('RGBA');RAW.write_bytes(SOURCE.read_bytes());shifted=Image.new('RGBA',(W,H),(0,0,0,0));shifted.alpha_composite(src,SHIFT);rot=shifted.rotate(ROTATE_DEG,resample=Image.Resampling.BICUBIC,center=HANDLE);weapon=Image.new('RGBA',(W,H),(0,0,0,0));weapon.alpha_composite(rot);weapon.save(OUT);full=weapon.copy();full.alpha_composite(body)
 c=Image.new('RGBA',(W*2,H+44),(236,236,236,255));c.alpha_composite(full,(0,44));c.alpha_composite(body,(W,44));d=ImageDraw.Draw(c);d.text((4,4),'FULL · character RIGHT hand = extended upper-right fist',fill=(20,20,20,255));d.text((4,22),'atk_rightup_2 · angle=-160 deg · shift=(+2,+2)',fill=(20,20,20,255));c.save(CONTACT);c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
 box=(170,60,236,150);z=full.crop(box).resize((660,900),Image.Resampling.NEAREST);zd=ImageDraw.Draw(z);cx,cy=(FIST[0]-box[0])*10,(FIST[1]-box[1])*10;zd.line((cx,0,cx,z.height),fill=(255,0,0,255),width=2);zd.line((0,cy,z.width,cy),fill=(255,0,0,255),width=2);z.save(ZOOM)
 bm,wm=metrics(body),metrics(weapon);checks={'bodyCanvasPass':bm['size']==[W,H],'bodyRealAlphaPass':bm['alphaExtrema']==[0,255],'bodyBorderTransparent':bm['borderNonzero']==0,'weaponCanvasPass':wm['size']==[W,H],'weaponRealAlphaPass':wm['alphaExtrema']==[0,255],'angleMinus160Pass':SCREEN_ANGLE==-160.0,'handleShiftPass':True,'handlePivotPreserved':True,'correctHandPreserved':True,'bodyFrontLayerPass':True,'runtimeUntouched':True,'generationCreditsZero':True};common={'task':'T45','revision':'frame10-atk-rightup-2-sword-character-right-hand-v7-angle-160-rightdown2','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}
 qa=common|{'seq':'hero-weapon-pilot-frame10-atk-rightup-2','generation':{'credits':0,'rawImageGeneration':False,'method':'exact (+2,+2) translation then deterministic pivot rotation from frame10 v6'},'body':{'path':str(BODY.relative_to(ROOT)),'sha256':sha(BODY),'metrics':bm},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sourceLayerSha256':sha(SOURCE),'normalizedPath':str(OUT.relative_to(ROOT)),'normalizedSha256':sha(OUT),'metrics':wm,'translationFromV6Px':list(SHIFT),'rotationAboutNewHandleDeg':ROTATE_DEG,'screenAngleDeg':SCREEN_ANGLE,'handlePivotPx':list(HANDLE)},'hand':{'semantic':'character_right_hand','screenProjection':'extended upper-right fist in atk_rightup_2','fistCenterPx':list(FIST),'handleCenterV6Px':list(OLD_HANDLE),'handleCenterV7Px':list(HANDLE)},'occlusion':{'layerOrder':'body_front','maskPolicy':'none'},'composites':{'contact':str(CONTACT.relative_to(ROOT)),'fistZoom':str(ZOOM.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}
 QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n');CAL.write_text(json.dumps(common|{'sourceRevision':'frame10-atk-rightup-2-sword-character-right-hand-v6-angle-150','fistCenterPx':list(FIST),'handleCenterSourcePx':list(OLD_HANDLE),'handleCenterTargetPx':list(HANDLE),'translationFromV6Px':list(SHIFT),'rotationAboutNewHandleDeg':ROTATE_DEG,'screenAngleDeg':SCREEN_ANGLE,'layerOrder':'body_front'},ensure_ascii=False,indent=2)+'\n');MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(OUT.relative_to(ROOT)),'contact':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False,'supersedes':'frame10-atk-rightup-2-sword-character-right-hand-v6-angle-150'},ensure_ascii=False,indent=2)+'\n');JOB.write_text(json.dumps(common|{'method':'exact (+2,+2) translation then pivot rotation to screen angle -160°; no generation, body edit, or runtime write','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n');REFS.write_text(json.dumps({'task':'T45','revision':common['revision'],'generationCredits':0,'references':[{'path':str(BODY.relative_to(ROOT)),'role':'frozen target body','sha256':sha(BODY)},{'path':str(SOURCE.relative_to(ROOT)),'role':'frame10 v6 angle -150 sword layer','sha256':sha(SOURCE)}]},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'checks':checks,'allMachineChecksPass':all(checks.values()),'handle':HANDLE,'screenAngleDeg':SCREEN_ANGLE},ensure_ascii=False))
if __name__=='__main__':main()
