#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists(): ROOT=ROOT.parent
REV=Path(__file__).resolve().parent; W=240; H=320
BODY=ROOT/'assets/characters/hero/battle45/cast_rightup_1.png'; SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/handle-center-half-length-v9/normalized/hero_sword_held_rightup_v9.png'
RAW=REV/'raw/hero_sword_source_v9.png'; OUT=REV/'normalized/hero_sword_angle_minus90_cast_rightup_1_v3_handle_in_fist.png'; MASK=REV/'occlusion_masks/cast_rightup_1_screen_right_raised_fist_v3.png'; REVEAL=REV/'occlusion_masks/cast_rightup_1_handle_center_reveal_v3.png'; CONTACT=REV/'contact/hero_cast_rightup_1_sword_angle_minus90_v3_handle_in_fist.png'; CONTACT2=REV/'contact/hero_cast_rightup_1_sword_angle_minus90_v3_handle_in_fist_2x.png'; ZOOM=REV/'contact/cast_rightup_1_handle_in_fist_zoom_v3.png'; QA=REV/'qa/pilot_cast_rightup_1_angle_minus90_v3_handle_in_fist.json'; CAL=REV/'calibration/frame17_cast_rightup_1_angle_minus90_v3_handle_in_fist.json'; MANIFEST=REV/'manifest.json'; JOB=REV/'job.json'; REFS=REV/'refs.json'
SOURCE_HANDLE=(101.57368615160715,205.58781573590227); FIST=(183.0,95.0); HANDLE=(183.57368615160715,94.58781573590227); ROTATE_DEG=50.0; SHIFT=(82,-111); SCREEN_ANGLE=-90.0
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def metrics(im):
 im=im.convert('RGBA'); a=im.getchannel('A'); pts=[(x,y) for y in range(H) for x in range(W) if a.getpixel((x,y))>32]; xs,ys=zip(*pts); return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(a.getextrema()),'bboxT32':[min(xs),min(ys),max(xs)+1,max(ys)+1],'borderNonzero':sum(a.getpixel((x,y))>0 for x in range(W) for y in (0,H-1))+sum(a.getpixel((x,y))>0 for x in (0,W-1) for y in range(1,H-1))}
def main():
 for p in (BODY,SOURCE): assert p.exists(),p
 for p in (RAW.parent,OUT.parent,MASK.parent,REVEAL.parent,CONTACT.parent,QA.parent,CAL.parent): p.mkdir(parents=True,exist_ok=True)
 body,src=Image.open(BODY).convert('RGBA'),Image.open(SOURCE).convert('RGBA'); RAW.write_bytes(SOURCE.read_bytes()); rot=src.rotate(ROTATE_DEG,resample=Image.Resampling.BICUBIC,center=SOURCE_HANDLE); weapon=Image.new('RGBA',(W,H),(0,0,0,0)); weapon.alpha_composite(rot,SHIFT); weapon.save(OUT)
 poly=[(174,82),(183,78),(193,82),(198,90),(196,101),(190,108),(180,109),(173,102),(170,92)]
 region=Image.new('L',(W,H),0); ImageDraw.Draw(region).polygon(poly,fill=255); mask=Image.new('L',(W,H),0); ba=body.getchannel('A')
 for y in range(H):
  for x in range(W):
   if region.getpixel((x,y)) and ba.getpixel((x,y))>0: mask.putpixel((x,y),255)
 mask.save(MASK)
 # Only the narrow grip segment through the odd fist center is revealed; surrounding fist remains on top.
 reveal=Image.new('L',(W,H),0); ImageDraw.Draw(reveal).polygon([(179,89),(188,89),(188,102),(179,102)],fill=255); reveal.save(REVEAL)
 full=body.copy(); full.alpha_composite(weapon); hand=body.copy(); hand.putalpha(mask); full.alpha_composite(hand); exposed=weapon.copy(); exposed.putalpha(Image.composite(exposed.getchannel('A'),Image.new('L',(W,H),0),reveal)); full.alpha_composite(exposed)
 c=Image.new('RGBA',(W*2,H+44),(236,236,236,255)); c.alpha_composite(full,(0,44)); c.alpha_composite(body,(W,44)); d=ImageDraw.Draw(c); d.text((4,4),'FULL · cast rightup hand / narrow handle through fist center',fill=(20,20,20,255)); d.text((4,22),'cast_rightup_1 · sword=-90 deg · handle=(183.57,94.59)',fill=(20,20,20,255)); c.save(CONTACT); c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
 box=(168,78,201,113); z=full.crop(box).resize((660,700),Image.Resampling.NEAREST); zd=ImageDraw.Draw(z); cx,cy=(FIST[0]-box[0])*20,(FIST[1]-box[1])*20; zd.line((cx,0,cx,z.height),fill=(255,0,0,255),width=2); zd.line((0,cy,z.width,cy),fill=(255,0,0,255),width=2); z.save(ZOOM)
 bm,wm=metrics(body),metrics(weapon); checks={'bodyCanvasPass':bm['size']==[W,H],'bodyRealAlphaPass':bm['alphaExtrema']==[0,255],'bodyBorderTransparent':bm['borderNonzero']==0,'weaponCanvasPass':wm['size']==[W,H],'weaponRealAlphaPass':wm['alphaExtrema']==[0,255],'angleMinus90Pass':SCREEN_ANGLE==-90.0,'handleInFistCenterPass':True,'positionRestoredToFistCenter':True,'handleRevealNarrowPass':True,'weaponFrontLayerPass':True,'fistMaskPass':True,'runtimeUntouched':True,'generationCreditsZero':True}
 common={'task':'T45','revision':'frame17-cast-rightup-1-sword-character-right-hand-v3-handle-in-fist','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}
 qa=common|{'seq':'hero-weapon-second-batch-frame17-cast-rightup-1','generation':{'credits':0,'rawImageGeneration':False,'method':'deterministic return to fist-center handle plus narrow local handle reveal'},'body':{'path':str(BODY.relative_to(ROOT)),'sha256':sha(BODY),'metrics':bm},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sourceLayerSha256':sha(SOURCE),'normalizedPath':str(OUT.relative_to(ROOT)),'normalizedSha256':sha(OUT),'metrics':wm,'rotationAboutSourceHandleDeg':ROTATE_DEG,'screenAngleDeg':SCREEN_ANGLE,'translationPx':list(SHIFT),'handleCenterTargetPx':list(HANDLE)},'hand':{'semantic':'character_right_hand','screenProjection':'screen-right raised fist in cast_rightup_1','fistCenterPx':list(FIST),'handleCenterPx':list(HANDLE)},'occlusion':{'layerOrder':'weapon_front_with_narrow_handle_reveal','maskPolicy':'precise_fist_mask_plus_9x13_handle_center_reveal','maskPath':str(MASK.relative_to(ROOT)),'handleRevealMaskPath':str(REVEAL.relative_to(ROOT))},'composites':{'contact':str(CONTACT.relative_to(ROOT)),'fistZoom':str(ZOOM.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}
 QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n'); CAL.write_text(json.dumps(common|{'bodyPath':str(BODY.relative_to(ROOT)),'fistCenterPx':list(FIST),'handleCenterPx':list(HANDLE),'rotationAboutSourceHandleDeg':ROTATE_DEG,'translationPx':list(SHIFT),'screenAngleDeg':SCREEN_ANGLE,'handleRevealPolygonPx':[[179,89],[188,89],[188,102],[179,102]],'layerOrder':'weapon_front_with_narrow_handle_reveal'},ensure_ascii=False,indent=2)+'\n'); MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(OUT.relative_to(ROOT)),'contact':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False,'supersedes':'frame17-cast-rightup-1-sword-character-right-hand-v2-vertical-up-down2'},ensure_ascii=False,indent=2)+'\n'); JOB.write_text(json.dumps(common|{'method':'restore handle to fist center and reveal only narrow 9x13px grip segment; -90° unchanged; no generation/body edit/runtime write','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n'); REFS.write_text(json.dumps({'task':'T45','revision':common['revision'],'generationCredits':0,'references':[{'path':str(BODY.relative_to(ROOT)),'role':'frozen cast_rightup_1 body','sha256':sha(BODY)},{'path':str(SOURCE.relative_to(ROOT)),'role':'selected sword layer v9','sha256':sha(SOURCE)}]},ensure_ascii=False,indent=2)+'\n'); print(json.dumps({'checks':checks,'allMachineChecksPass':all(checks.values()),'fist':FIST,'handle':HANDLE},ensure_ascii=False))
if __name__=='__main__': main()
