#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists():ROOT=ROOT.parent
REV=Path(__file__).resolve().parent;W=240;H=320
BODY=ROOT/'assets/characters/hero/battle45/atk_rightup_1.png';SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/frame09-atk-rightup-1-sword-character-right-hand-v4-leftdown2/normalized/hero_sword_vertical_atk_rightup_1_v4_leftdown2.png'
RAW=REV/'raw/hero_sword_vertical_atk_rightup_1_v4.png';OUT=REV/'normalized/hero_sword_vertical_atk_rightup_1_v5_down1.png';CONTACT=REV/'contact/hero_atk_rightup_1_sword_vertical_v5_down1.png';CONTACT2=REV/'contact/hero_atk_rightup_1_sword_vertical_v5_down1_2x.png';ZOOM=REV/'contact/atk_rightup_1_correct_hand_zoom_v5_down1.png';QA=REV/'qa/pilot_atk_rightup_1_vertical_grip_v5_down1.json';CAL=REV/'calibration/frame09_atk_rightup_1_vertical_grip_v5_down1.json';MANIFEST=REV/'manifest.json';JOB=REV/'job.json';REFS=REV/'refs.json'
SHIFT=(0,1);FIST=(164.0,181.0);SOURCE_HANDLE=(157.57368615160715,182.58781573590227);TARGET_HANDLE=(157.57368615160715,183.58781573590227)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def metrics(im):
 im=im.convert('RGBA');a=im.getchannel('A');pts=[(x,y) for y in range(H) for x in range(W) if a.getpixel((x,y))>32];xs,ys=zip(*pts);return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(a.getextrema()),'bboxT32':[min(xs),min(ys),max(xs)+1,max(ys)+1],'borderNonzero':sum(a.getpixel((x,y))>0 for x in range(W) for y in (0,H-1))+sum(a.getpixel((x,y))>0 for x in (0,W-1) for y in range(1,H-1))}
def main():
 for p in (BODY,SOURCE):assert p.exists(),p
 for p in (RAW.parent,OUT.parent,CONTACT.parent,QA.parent,CAL.parent):p.mkdir(parents=True,exist_ok=True)
 body,src=Image.open(BODY).convert('RGBA'),Image.open(SOURCE).convert('RGBA');RAW.write_bytes(SOURCE.read_bytes());weapon=Image.new('RGBA',(W,H),(0,0,0,0));weapon.alpha_composite(src,SHIFT);weapon.save(OUT);full=weapon.copy();full.alpha_composite(body)
 c=Image.new('RGBA',(W*2,H+44),(236,236,236,255));c.alpha_composite(full,(0,44));c.alpha_composite(body,(W,44));d=ImageDraw.Draw(c);d.text((4,4),'FULL · character RIGHT hand = lower screen-right forward fist',fill=(20,20,20,255));d.text((4,22),'atk_rightup_1 · vertical -90 deg · v4 down 1px',fill=(20,20,20,255));c.save(CONTACT);c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
 box=(132,144,190,202);z=full.crop(box).resize((696,696),Image.Resampling.NEAREST);zd=ImageDraw.Draw(z);cx,cy=(FIST[0]-box[0])*12,(FIST[1]-box[1])*12;zd.line((cx,0,cx,z.height),fill=(255,0,0,255),width=2);zd.line((0,cy,z.width,cy),fill=(255,0,0,255),width=2);z.save(ZOOM)
 bm,wm=metrics(body),metrics(weapon);checks={'bodyCanvasPass':bm['size']==[W,H],'bodyRealAlphaPass':bm['alphaExtrema']==[0,255],'bodyBorderTransparent':bm['borderNonzero']==0,'weaponCanvasPass':wm['size']==[W,H],'weaponRealAlphaPass':wm['alphaExtrema']==[0,255],'verticalAnglePreserved':True,'exactDown1TranslationPass':True,'correctHandPreserved':True,'bodyFrontLayerPass':True,'runtimeUntouched':True,'generationCreditsZero':True};common={'task':'T45','revision':'frame09-atk-rightup-1-sword-character-right-hand-v5-down1','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}
 qa=common|{'seq':'hero-weapon-pilot-frame09-atk-rightup-1','generation':{'credits':0,'rawImageGeneration':False,'method':'exact integer RGBA translation of frame09 v4 layer'},'body':{'path':str(BODY.relative_to(ROOT)),'sha256':sha(BODY),'metrics':bm},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sourceLayerSha256':sha(SOURCE),'normalizedPath':str(OUT.relative_to(ROOT)),'normalizedSha256':sha(OUT),'metrics':wm,'screenAngleDeg':-90.0,'translationFromV4Px':list(SHIFT)},'hand':{'semantic':'character_right_hand','screenProjection':'lower screen-right forward fist in atk_rightup_1','fistCenterPx':list(FIST),'handleCenterV4Px':list(SOURCE_HANDLE),'handleCenterV5Px':list(TARGET_HANDLE)},'occlusion':{'layerOrder':'body_front','maskPolicy':'none'},'composites':{'contact':str(CONTACT.relative_to(ROOT)),'fistZoom':str(ZOOM.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}
 QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n');CAL.write_text(json.dumps(common|{'sourceRevision':'frame09-atk-rightup-1-sword-character-right-hand-v4-leftdown2','fistCenterPx':list(FIST),'handleCenterSourcePx':list(SOURCE_HANDLE),'handleCenterTargetPx':list(TARGET_HANDLE),'translationFromV4Px':list(SHIFT),'screenAngleDeg':-90.0,'layerOrder':'body_front'},ensure_ascii=False,indent=2)+'\n');MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(OUT.relative_to(ROOT)),'contact':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False,'supersedes':'frame09-atk-rightup-1-sword-character-right-hand-v4-leftdown2'},ensure_ascii=False,indent=2)+'\n');JOB.write_text(json.dumps(common|{'method':'exact (0,+1) integer translation; no rotation, generation, body edit, or runtime write','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n');REFS.write_text(json.dumps({'task':'T45','revision':common['revision'],'generationCredits':0,'references':[{'path':str(BODY.relative_to(ROOT)),'role':'frozen target body','sha256':sha(BODY)},{'path':str(SOURCE.relative_to(ROOT)),'role':'frame09 v4 vertical sword layer','sha256':sha(SOURCE)}]},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'checks':checks,'allMachineChecksPass':all(checks.values()),'handle':TARGET_HANDLE},ensure_ascii=False))
if __name__=='__main__':main()
