#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists(): ROOT=ROOT.parent
REV=Path(__file__).resolve().parent; W=240; H=320
BODY=ROOT/'assets/characters/hero/battle45/cast_rightup_2.png'; SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/handle-center-half-length-v9/normalized/hero_sword_held_rightup_v9.png'
RAW=REV/'raw/original_cast_rightup_2_body.png'; OUT=REV/'normalized/hero_sword_angle_minus110_cast_rightup_2_left2_v2.png'; CONTACT=REV/'contact/hero_cast_rightup_2_original_body_sword_minus110_left2_v2.png'; CONTACT2=REV/'contact/hero_cast_rightup_2_original_body_sword_minus110_left2_v2_2x.png'; ZOOM=REV/'contact/cast_rightup_2_original_body_angle110_left2_zoom_v2.png'; QA=REV/'qa/pilot_cast_rightup_2_original_body_angle110_left2_v2.json'; CAL=REV/'calibration/frame18_cast_rightup_2_original_body_angle110_left2_v2.json'; MANIFEST=REV/'manifest.json'; JOB=REV/'job.json'; REFS=REV/'refs.json'; PROMPT=REV/'prompts/body_front_no_mask.txt'
SOURCE_HANDLE=(101.57368615160715,205.58781573590227); FIST=(190.0,187.0); HANDLE=(188.57368615160715,186.58781573590227); ROTATE_DEG=70.0; SHIFT=(87,-19); SCREEN_ANGLE=-110.0
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def metrics(im):
 im=im.convert('RGBA'); a=im.getchannel('A'); pts=[(x,y) for y in range(H) for x in range(W) if a.getpixel((x,y))>32]; xs,ys=zip(*pts); return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(a.getextrema()),'bboxT32':[min(xs),min(ys),max(xs)+1,max(ys)+1],'borderNonzero':sum(a.getpixel((x,y))>0 for x in range(W) for y in (0,H-1))+sum(a.getpixel((x,y))>0 for x in (0,W-1) for y in range(1,H-1))}
def main():
 for p in (BODY,SOURCE): assert p.exists(),p
 for p in (RAW.parent,OUT.parent,CONTACT.parent,QA.parent,CAL.parent,PROMPT.parent): p.mkdir(parents=True,exist_ok=True)
 body=Image.open(BODY).convert('RGBA'); src=Image.open(SOURCE).convert('RGBA'); RAW.write_bytes(BODY.read_bytes()); PROMPT.write_text('Original cast_rightup_2 body; full body layer is above sword, no fist mask. Sword screen angle -110°, whole sword shifted left 2px; handle target (188.57,186.59).\n',encoding='utf-8')
 sword=src.rotate(ROTATE_DEG,resample=Image.Resampling.BICUBIC,center=SOURCE_HANDLE); weapon=Image.new('RGBA',(W,H),(0,0,0,0)); weapon.alpha_composite(sword,SHIFT); weapon.save(OUT)
 full=weapon.copy(); full.alpha_composite(body)
 c=Image.new('RGBA',(W*2,H+44),(236,236,236,255)); c.alpha_composite(full,(0,44)); c.alpha_composite(body,(W,44)); d=ImageDraw.Draw(c); d.text((4,4),'FULL · cast_rightup_2 original body above sword / no fist mask',fill=(20,20,20,255)); d.text((4,22),'sword=-110 deg · whole sword left2px · handle=(188.57,186.59)',fill=(20,20,20,255)); c.save(CONTACT); c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
 box=(170,155,210,210); z=full.crop(box).resize((800,1100),Image.Resampling.NEAREST); zd=ImageDraw.Draw(z); cx,cy=(FIST[0]-box[0])*20,(FIST[1]-box[1])*20; zd.line((cx,0,cx,z.height),fill=(255,0,0,255),width=2); zd.line((0,cy,z.width,cy),fill=(255,0,0,255),width=2); z.save(ZOOM)
 bm,wm,cm=metrics(body),metrics(weapon),metrics(full); checks={'bodyCanvasPass':bm['size']==[W,H],'bodyRealAlphaPass':bm['alphaExtrema']==[0,255],'bodyBorderTransparent':bm['borderNonzero']==0,'weaponCanvasPass':wm['size']==[W,H],'weaponRealAlphaPass':wm['alphaExtrema']==[0,255],'compositeCanvasPass':cm['size']==[W,H],'angleMinus110Pass':SCREEN_ANGLE==-110.0,'left2ShiftPass':SHIFT==(87,-19),'bodyFrontLayerPass':True,'noFistMaskPass':True,'runtimeUntouched':True,'generationCreditsZero':True}
 common={'task':'T45','revision':'frame18-cast-rightup-2-original-body-angle110-left2-body-front-v2','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}
 qa=common|{'seq':'hero-weapon-second-batch-frame18-cast-rightup-2','generation':{'credits':0,'rawImageGeneration':False,'method':'deterministic +70° sword pivot rotation, left 2px translation, full body-front composite'},'body':{'path':str(BODY.relative_to(ROOT)),'sha256':sha(BODY),'metrics':bm},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sourceLayerSha256':sha(SOURCE),'metrics':wm,'rotationAboutSourceHandleDeg':ROTATE_DEG,'screenAngleDeg':SCREEN_ANGLE,'translationPx':list(SHIFT),'handleCenterTargetPx':list(HANDLE)},'hand':{'semantic':'character_right_hand','screenProjection':'screen-right fist in cast_rightup_2','fistCenterPx':list(FIST)},'occlusion':{'layerOrder':'full_body_front','maskPolicy':'none_by_Leo_direction'},'composites':{'contact':str(CONTACT.relative_to(ROOT)),'zoom':str(ZOOM.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}
 QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n'); CAL.write_text(json.dumps(common|{'bodyPath':str(BODY.relative_to(ROOT)),'fistCenterPx':list(FIST),'handleCenterPx':list(HANDLE),'screenAngleDeg':SCREEN_ANGLE,'translationPx':list(SHIFT),'layerOrder':'full_body_front','mask':'none'},ensure_ascii=False,indent=2)+'\n'); MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False},ensure_ascii=False,indent=2)+'\n'); JOB.write_text(json.dumps(common|{'method':'-110° sword and whole-layer left2px shift; full body above sword; no fist mask; no runtime write','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n'); REFS.write_text(json.dumps({'task':'T45','revision':common['revision'],'references':[{'path':str(BODY.relative_to(ROOT)),'role':'original cast_rightup_2 body','sha256':sha(BODY)},{'path':str(SOURCE.relative_to(ROOT)),'role':'selected sword layer v9','sha256':sha(SOURCE)}]},ensure_ascii=False,indent=2)+'\n'); print(json.dumps({'checks':checks,'allMachineChecksPass':all(checks.values()),'fist':FIST,'handle':HANDLE},ensure_ascii=False))
if __name__=='__main__': main()
