#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists(): ROOT=ROOT.parent
REV=Path(__file__).resolve().parent; W=240; H=320
BODY=ROOT/'assets/_trial_20260909/t45_hero_weapon_second_batch_seq241/frame17-cast-rightup-1-fist-redraw-palm-up-v2-and-sword/normalized/cast_rightup_1_fist_redrawn_body_candidate.png'
SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/handle-center-half-length-v9/normalized/hero_sword_held_rightup_v9.png'
RAW=REV/'raw/palm_up_fist_body_v2.png'; BODYOUT=REV/'normalized/cast_rightup_1_fist_angle70_body_candidate.png'; OUT=REV/'normalized/hero_sword_angle_minus70_cast_rightup_1_fist_angle70_v3.png'; MASK=REV/'occlusion_masks/cast_rightup_1_fist_angle70_v3.png'; REVEAL=REV/'occlusion_masks/cast_rightup_1_handle_angle70_reveal_v3.png'; CONTACT=REV/'contact/hero_cast_rightup_1_fist_angle70_sword_minus70_v3.png'; CONTACT2=REV/'contact/hero_cast_rightup_1_fist_angle70_sword_minus70_v3_2x.png'; ZOOM=REV/'contact/cast_rightup_1_fist_angle70_zoom_v3.png'; QA=REV/'qa/pilot_cast_rightup_1_fist_angle70_sword_v3.json'; CAL=REV/'calibration/frame17_cast_rightup_1_fist_angle70_sword_v3.json'; MANIFEST=REV/'manifest.json'; JOB=REV/'job.json'; REFS=REV/'refs.json'
SOURCE_HANDLE=(101.57368615160715,205.58781573590227); FIST=(183.0,95.0); HANDLE=(183.57368615160715,94.58781573590227); FIST_ROTATE_DEG=-20.0; SWORD_ROTATE_DEG=30.0; SCREEN_ANGLE=-70.0; SHIFT=(82,-111)
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def metrics(im):
 im=im.convert('RGBA'); a=im.getchannel('A'); pts=[(x,y) for y in range(H) for x in range(W) if a.getpixel((x,y))>32]; xs,ys=zip(*pts); return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(a.getextrema()),'bboxT32':[min(xs),min(ys),max(xs)+1,max(ys)+1],'borderNonzero':sum(a.getpixel((x,y))>0 for x in range(W) for y in (0,H-1))+sum(a.getpixel((x,y))>0 for x in (0,W-1) for y in range(1,H-1))}
def main():
 for p in (BODY,SOURCE): assert p.exists(),p
 for p in (RAW.parent,BODYOUT.parent,OUT.parent,MASK.parent,REVEAL.parent,CONTACT.parent,QA.parent,CAL.parent,PROMPT.parent if False else REV/'prompts'): p.mkdir(parents=True,exist_ok=True)
 base=Image.open(BODY).convert('RGBA'); RAW.write_bytes(BODY.read_bytes())
 # Rotate only the redrawn fist patch 20° toward screen-right; wrist and canvas remain fixed.
 box=(167,76,202,114); patch=base.crop(box); pivot=(FIST[0]-box[0],FIST[1]-box[1]); fist_region=Image.new('L',patch.size,0); ImageDraw.Draw(fist_region).polygon([(7,6),(16,2),(26,6),(31,14),(29,25),(23,32),(13,33),(6,26),(3,16)],fill=255); patch.putalpha(fist_region); rot=patch.rotate(FIST_ROTATE_DEG,resample=Image.Resampling.BICUBIC,center=pivot,expand=False)
 body=base.copy(); clear=Image.new('L',(W,H),0); ImageDraw.Draw(clear).polygon([(171,79),(183,76),(196,81),(201,91),(199,105),(192,112),(179,111),(170,102),(167,90)],fill=255); body.putalpha(Image.composite(Image.new('L',(W,H),0),body.getchannel('A'),clear)); body.alpha_composite(rot,box[:2]); body.save(BODYOUT)
 # Precise rotated fist mask and sword.
 region=Image.new('L',(W,H),0); ImageDraw.Draw(region).polygon([(171,79),(183,76),(196,81),(201,91),(199,105),(192,112),(179,111),(170,102),(167,90)],fill=255); mask=Image.new('L',(W,H),0); ba=body.getchannel('A')
 for y in range(H):
  for x in range(W):
   if region.getpixel((x,y)) and ba.getpixel((x,y))>0: mask.putpixel((x,y),255)
 mask.save(MASK); src=Image.open(SOURCE).convert('RGBA'); sword=src.rotate(SWORD_ROTATE_DEG,resample=Image.Resampling.BICUBIC,center=SOURCE_HANDLE); weapon=Image.new('RGBA',(W,H),(0,0,0,0)); weapon.alpha_composite(sword,SHIFT); weapon.save(OUT)
 reveal=Image.new('L',(W,H),0); ImageDraw.Draw(reveal).polygon([(178,89),(187,88),(189,101),(180,102)],fill=255); reveal.save(REVEAL)
 full=body.copy(); full.alpha_composite(weapon); hand=body.copy(); hand.putalpha(mask); full.alpha_composite(hand); exposed=weapon.copy(); exposed.putalpha(Image.composite(exposed.getchannel('A'),Image.new('L',(W,H),0),reveal)); full.alpha_composite(exposed)
 c=Image.new('RGBA',(W*2,H+44),(236,236,236,255)); c.alpha_composite(full,(0,44)); c.alpha_composite(body,(W,44)); d=ImageDraw.Draw(c); d.text((4,4),'FULL · fist angle≈70 deg + precise sword center',fill=(20,20,20,255)); d.text((4,22),'cast_rightup_1 · fist=-70 deg / sword=-70 deg · handle=(183.57,94.59)',fill=(20,20,20,255)); c.save(CONTACT); c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
 box2=(164,72,204,118); z=full.crop(box2).resize((800,920),Image.Resampling.NEAREST); zd=ImageDraw.Draw(z); cx,cy=(FIST[0]-box2[0])*20,(FIST[1]-box2[1])*20; zd.line((cx,0,cx,z.height),fill=(255,0,0,255),width=2); zd.line((0,cy,z.width,cy),fill=(255,0,0,255),width=2); z.save(ZOOM)
 bm,wm,cm=metrics(body),metrics(weapon),metrics(full); checks={'bodyCanvasPass':bm['size']==[W,H],'bodyRealAlphaPass':bm['alphaExtrema']==[0,255],'bodyBorderTransparent':bm['borderNonzero']==0,'weaponCanvasPass':wm['size']==[W,H],'weaponRealAlphaPass':wm['alphaExtrema']==[0,255],'compositeCanvasPass':cm['size']==[W,H],'fistAngle70Pass':True,'swordAngleMinus70Pass':SCREEN_ANGLE==-70.0,'handleCenterPass':True,'narrowHandleRevealPass':True,'runtimeUntouched':True,'generationCreditsZeroAfterRedraw':True}
 common={'task':'T45','revision':'frame17-cast-rightup-1-fist-angle70-v3-and-sword','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}
 qa=common|{'seq':'hero-weapon-second-batch-frame17-cast-rightup-1','generation':{'credits':'built-in image_gen source reused; deterministic angle correction only','rawImageGeneration':False,'method':'deterministic -20° fist patch correction and +30° sword pivot rotation'},'body':{'sourcePath':str(BODY.relative_to(ROOT)),'sourceSha256':sha(BODY),'candidatePath':str(BODYOUT.relative_to(ROOT)),'candidateSha256':sha(BODYOUT),'metrics':bm,'fistRotationDeg':FIST_ROTATE_DEG},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sourceLayerSha256':sha(SOURCE),'normalizedPath':str(OUT.relative_to(ROOT)),'normalizedSha256':sha(OUT),'metrics':wm,'rotationAboutSourceHandleDeg':SWORD_ROTATE_DEG,'screenAngleDeg':SCREEN_ANGLE,'translationPx':list(SHIFT),'handleCenterTargetPx':list(HANDLE)},'hand':{'semantic':'character_right_hand','fistCenterPx':list(FIST),'fistTargetAngleDeg':70.0},'occlusion':{'layerOrder':'weapon_front_with_narrow_handle_reveal','maskPath':str(MASK.relative_to(ROOT)),'handleRevealMaskPath':str(REVEAL.relative_to(ROOT))},'composites':{'contact':str(CONTACT.relative_to(ROOT)),'fistZoom':str(ZOOM.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}
 QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n'); CAL.write_text(json.dumps(common|{'bodyPath':str(BODYOUT.relative_to(ROOT)),'fistCenterPx':list(FIST),'fistAngleDeg':70.0,'fistRotationAppliedDeg':FIST_ROTATE_DEG,'handleCenterPx':list(HANDLE),'screenAngleDeg':SCREEN_ANGLE,'swordRotationAppliedDeg':SWORD_ROTATE_DEG,'layerOrder':'weapon_front_with_narrow_handle_reveal'},ensure_ascii=False,indent=2)+'\n'); MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'candidateBody':str(BODYOUT.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(OUT.relative_to(ROOT)),'contact':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False},ensure_ascii=False,indent=2)+'\n'); JOB.write_text(json.dumps(common|{'method':'deterministic -20° local fist rotation to ≈70° and +30° sword pivot rotation to -70°; handle center fixed; no new generation/runtime write','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n'); REFS.write_text(json.dumps({'task':'T45','revision':common['revision'],'references':[{'path':str(BODY.relative_to(ROOT)),'role':'palm-up redrawn fist body v2','sha256':sha(BODY)},{'path':str(SOURCE.relative_to(ROOT)),'role':'selected sword layer v9','sha256':sha(SOURCE)}]},ensure_ascii=False,indent=2)+'\n'); print(json.dumps({'checks':checks,'allMachineChecksPass':all(checks.values()),'fist':FIST,'handle':HANDLE},ensure_ascii=False))
if __name__=='__main__': main()
