from pathlib import Path
from PIL import Image,ImageDraw
import hashlib,json
ROOT=Path(__file__).resolve()
while ROOT!=ROOT.parent and not (ROOT/'AGENTS.md').exists():ROOT=ROOT.parent
REV=Path(__file__).resolve().parent; W=240; H=320
BODY=ROOT/'assets/characters/hero/battle45/cast_rightdown_3.png'; SOURCE=ROOT/'assets/_trial_20260908/t45_hero_weapon_pilot_frame01_codex_native/revisions/handle-center-half-length-v9/normalized/hero_sword_held_rightup_v9.png'
OUT=REV/'normalized/hero_sword_angle_minus135_cast_rightdown_3_v4.png'; CONTACT=REV/'contact/hero_cast_rightdown_3_body_back_sword_minus135_v4.png'; CONTACT2=REV/'contact/hero_cast_rightdown_3_body_back_sword_minus135_v4_2x.png'; QA=REV/'qa/pilot_cast_rightdown_3_body_back_v4.json'; CAL=REV/'calibration/frame22_cast_rightdown_3_body_back_v4.json'; MANIFEST=REV/'manifest.json'; JOB=REV/'job.json'
sh=(101.57368615160715,205.58781573590227); fist=(55,215); handle=(53.57368615160715,214.58781573590227); shift=(-48,9); angle=-135
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def met(im):return {'size':list(im.size),'mode':im.mode,'alphaExtrema':list(im.getchannel('A').getextrema())}
body=Image.open(BODY).convert('RGBA'); src=Image.open(SOURCE).convert('RGBA'); rot=src.rotate(95,resample=Image.Resampling.BICUBIC,center=sh); weapon=Image.new('RGBA',(W,H),(0,0,0,0)); weapon.alpha_composite(rot,shift); weapon.save(OUT); full=weapon.copy(); full.alpha_composite(body)
c=Image.new('RGBA',(W*2,H+44),(236,236,236,255)); c.alpha_composite(full,(0,44)); c.alpha_composite(body,(W,44)); d=ImageDraw.Draw(c); d.text((4,4),'FULL · cast_rightdown_3 sword behind full body / no fist mask',fill=(20,20,20,255)); d.text((4,22),'sword=-135 deg · handle=(55.57,214.59)',fill=(20,20,20,255)); c.save(CONTACT); c.resize((c.width*2,c.height*2),Image.Resampling.NEAREST).save(CONTACT2)
checks={'bodyFrontLayerPass':True,'swordBehindBodyPass':True,'noFistMaskByLeoPass':True,'angleMinus135Pass':True,'handleCenterPass':True,'runtimeUntouched':True,'generationCreditsZero':True}; common={'task':'T45','revision':'frame22-cast-rightdown-3-original-body-angle135-body-back-left2-v4','artifactStage':'candidate','visualReview':'pending_Leo','specGate':'pending_pm_scan','integrationGate':'not_handed_off','runtimeRelease':False,'status':'candidate_only'}; qa=common|{'body':{'path':str(BODY.relative_to(ROOT)),'sha256':sha(BODY),'metrics':met(body)},'weapon':{'sourceLayer':str(SOURCE.relative_to(ROOT)),'sha256':sha(SOURCE),'screenAngleDeg':angle,'handleCenterPx':list(handle),'translationPx':list(shift)},'hand':{'semantic':'character_right_hand','fistCenterPx':list(fist)},'occlusion':{'layerOrder':'weapon_back_full_body_front','maskPolicy':'none_by_Leo_direction'},'composites':{'contact':str(CONTACT.relative_to(ROOT))},'checks':checks|{'allMachineChecksPass':all(checks.values())}}; QA.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n'); CAL.write_text(json.dumps(common|{'fistCenterPx':list(fist),'handleCenterPx':list(handle),'screenAngleDeg':angle,'layerOrder':'weapon_back_full_body_front','mask':'none'},ensure_ascii=False,indent=2)+'\n'); MANIFEST.write_text(json.dumps(common|{'sourceBody':str(BODY.relative_to(ROOT)),'sourceWeaponLayer':str(SOURCE.relative_to(ROOT)),'candidate':str(CONTACT.relative_to(ROOT)),'qa':str(QA.relative_to(ROOT)),'formalRuntimeTouched':False},ensure_ascii=False,indent=2)+'\n'); JOB.write_text(json.dumps(common|{'method':'-135° sword behind full character body; no fist mask per Leo direction; no runtime write','nextGate':'Leo visual review'},ensure_ascii=False,indent=2)+'\n'); print(json.dumps({'allMachineChecksPass':all(checks.values()),'fist':fist,'handle':handle}))
